name: MLOps Pipeline

on:
  push:
    branches:
      - develop

jobs:
  train-and-deploy:
    environment: VASTAI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: SSH to VAST.AI and train
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ vars.VASTAI_IP }}
      #     username: ${{ vars.VASTAI_USER }}
      #     port: ${{ vars.VASTAI_PORT }}
      #     key: ${{ secrets.VASTAI_SSH_KEY }}
      #     timeout: 1800s
      #     command_timeout: 1800s
      #     script: |
      #       cd /workspace/llm-finetune-mlops/
      #       git pull
      #       source .venv/bin/activate
      #       python -m pip install --upgrade pip
      #       pip install -r requirements.txt
      #       # python scripts/train.py
      #       rm -r outputs/checkpoint*
      #       zip -r outputs.zip outputs
      #       source /venv/main/bin/activate
      #       cd /workspace/llm-finetune-mlops
      #       aws s3 cp outputs.zip s3://zett-vast-ai/outputs.zip



      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.EC2_IP }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 1800s
          command_timeout: 1800s
          script: |
            echo "Starting deployment on EC2 instance..."
            # aws s3 cp s3://zett-vast-ai/outputs.zip /home/ubuntu/project/llm-finetune-mlops/outputs.zip
            cd /home/ubuntu/project/llm-finetune-mlops
            # git pull
            # unzip -o outputs.zip
            echo "Unzipped outputs.zip successfully."
            sudo apt-get install -y procps

            pids=$(ps -ef | grep gradio_app.py | grep -v grep | awk '{print $2}')
            if [ -n "$pids" ]; then
              kill -9 $pids
              echo "Killed Gradio app processes."
            else
              echo "No Gradio app process found."
            fi

            echo "Old Gradio app process killed, if it was running."
            bash -lc "source /home/ubuntu/.venv/bin/activate && nohup python scripts/gradio_app.py > gradio.log 2>&1 & disown"
            echo "Gradio app started successfully."

